<?xml version="1.0" encoding="UTF-8"?>
<ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru" start="1463086680753" stop="1463086698160">
	<name>LoginPage</name>
	<title>LoginPage</title>
	<test-cases>
		<test-case start="1463086680753" stop="1463086698159" status="failed">
			<name>enter user name</name>
			<title>enter user name</title>
			<description></description>
			<labels>
			</labels>
			<parameters>
			</parameters>
			<steps>
			</steps>
			<attachments>
				<attachment title="Screenshot" source="892eaca3-b3b0-479e-a123-2115cd8a38d2-attachment.png" type="image/png" size="81685"/>
			</attachments>
			<failure>
				<message>Expected true to be false.</message>
				<stack-trace>Error: Failed expectation
    at Object.&lt;anonymous&gt; (C:\Git\BlueprintSys\blueprint\blueprint-automationframework\UI-e2e-Tests\UI-e2e-Tests\UI-e2e-Tests\Specs\Storyteller\LoginTestSpec.ts:33:47)
    at C:\Users\makbar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:96:23
    at new Promise (C:\Users\makbar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1043:7)
    at controlFlowExecute (C:\Users\makbar\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:82:18)
    at TaskQueue.execute_ (C:\Users\makbar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2790:14)
    at TaskQueue.executeNext_ (C:\Users\makbar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2773:21)
    at C:\Users\makbar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2697:25
    at C:\Users\makbar\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)</stack-trace>
			</failure>
		</test-case>
	</test-cases>
</ns2:test-suite>